language: java

sudo: false

install: true # skip installation step

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

script: ./gradlew assemble check -PmavenUser=x -PmavenPassword=x

after_success:
  - ./gradlew jacocoTestReport coveralls -PmavenUser=x -PmavenPassword=x

notifications:
  email: false